### ISSUE TITLE
Tracking for RFC Process Update RFC #0300

### ISSUE THREAD

**Issue by kategengler** [test-org-kmg/tracking#4]
### Tracking for RFC Process Update [RFC #0300](emberjs/rfcs#0300)

Champion: Katie Gengler

---

### Ember CLI:

- [x] Move ember-cli/rfcs merged RFCs into emberjs/rfcs
- [x] Close all outstanding issues and PRs on ember-cli-rfcs 
- [x] Archive ember-cli/rfcs

### Steering:

- [ ] Update emberjs/rfcs README to reflect the RFC
- [x] Update emberjs/rfcs templates to reflect the RFC
- [ ] Create a way to track merged RFCs
- [ ] Ensure teams adopt updated RFC process & review & plan RFCs

### Other tasks:

- [ ] Backfill Champions for on-going RFCs (assign to RFC PR)
- [ ] Backfill Header format to older RFCs

## Open Questions

- Should the champion also be specified in the header of the RFC template?
- Can an RFC have multiple Champions?
