### ISSUE TITLE
Tracking for Remove jQuery by Default RFC #0386

### ISSUE THREAD

**Issue by kategengler** [test-org-kmg/tracking#5]
# EXAMPLE TRACKING - mentions have been scrubbed and links broken to not pollute github

## [RFC #0386](https://github.com/emerjs/rfcs#0386) Tracking for Remove jQuery by Default 

Champion: Robert Jackson

---

> All teams need to consider a merged RFC to plan any required work. Each team should comment on or edit this with links to issues for the work (or a note to the effect of "No work required"). 

#### [ember.js](https://github.com/emberjs/ember.js)

- [x] add a (universal, non-silenceable) deprecation warning to `Ember.$()`
🔒@-person-, PR: https://github.com/emerjs/ember.js/pull/17489
- [x] add a deprecation warning to `this.$()` in an `Ember.Component`
🔒@-person-, PR: https://github.com/emerjs/ember.js/pull/17488
- [x] make sure user sees deprecation warning of jQuery integration itself, i.e. neither the `jquery-integration` optional feature flag is set to false nor `@ember/jquery` has been installed.
🔒@-person-, PR: https://github.com/emer-cli/ember-cli/pull/8399
- [x] wrap all jQuery related code for svelte
🔒@-person-, PR: https://github.com/emerjs/ember.js/pull/17525

##### Removal phase (4.0)

- [ ] remove deprecated functions
- [ ] remove the jQuery specific code paths in the EventDispatcher

#### [@ember/jquery](https://github.com/emberjs/ember-jquery)

- [x] Add support for `Component.$()`
🔒@-person-, WIP PR: https://github.com/emerjs/ember-jquery/pull/27
- [ ] Add jQuery-based EventDispatcher replacement 
🔒@-person-, WIP PR: https://github.com/emerjs/ember-jquery/pull/31
- [x] Make `import $ from 'jquery';` work
🔒@-person-, PR: https://github.com/emerjs/ember-jquery/pull/33

#### [@ember/test-helpers](https://github.com/emberjs/ember-test-helpers)

- [x] Add a deprecation warning to `this.$()` in component integration tests, based on `setupRenderingTest()`
🔒@-person-, PR: https://github.com/emerjs/ember-test-helpers/pull/543

#### [ember-cli](https://github.com/ember-cli/ember-cli)

- [ ] Update app blueprint, stage 1: Update `@ember/jquery` to latest version
PR: https://github.com/ember-cli/emer-cli/pull/8396
- [ ] Update app blueprint, stage 2: remove jQuery
🔒@-person-, PR: https://github.com/emer-cli/ember-cli/pull/8394

#### [ember-cli-babel](https://github.com/babel/emer-cli-babel)

- [x] Do not transpile `import $ from 'jquery';` to `Ember.$` if the right version of `@ember/jquery` is present
🔒@-person-, PR: https://github.com/babel/emer-cli-babel/pull/261

#### [ember-data](https://github.com/emerjs/data)

- [ ] Make ember-data work with ember-fetch
🔒@-person- PR: https://github.com/emerjs/data/pull/5386

### Learning Team:

TODO: Do any docs need to be updated?

#### Website

- [x] Add a [deprecation guide](https://emberjs.github.io/rfcs/0386-remove-jquery.html#how-we-teach-this)
🔒@-person- PR: https://github.com/emer-learn/deprecation-app/pull/255

### Steering Committee:
No work expected
